{"name": "Тест на создание фейковых пользователей", "status": "broken", "statusDetails": {"message": "AttributeError: 'Database' object has no attribute 'test_create_fake_users'. Did you mean: 'create_fake_users'?", "trace": "@allure.title(\"Тест на создание фейковых пользователей\")\n    def test_create_fake_users():\n>       db.test_create_fake_users(2)\nE       AttributeError: 'Database' object has no attribute 'test_create_fake_users'. Did you mean: 'create_fake_users'?\n\napi_test.py:11: AttributeError"}, "start": 1703592363289, "stop": 1703592363289, "uuid": "aa724467-7ca3-420a-96eb-b6f216f4f80a", "historyId": "e285d5f3ae46e1417f420f55d5bb4915", "testCaseId": "e285d5f3ae46e1417f420f55d5bb4915", "fullName": "api_test#test_create_fake_users", "labels": [{"name": "suite", "value": "api_test"}, {"name": "host", "value": "DESKTOP-TV6CGIP"}, {"name": "thread", "value": "11068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_test"}]}